config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "landings#show"
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :bars do
    member do
      post "join" => "bar_gig_memberships#create"
      delete "leave" => "bar_gig_memberships#destroy"
    end
    member do
      get "report" => "reports#show"
    end
    resources :shifts
  end

  resources :shifts do
    member do
      post "take" => "shift_memberships#create"
      delete "return" => "shift_memberships#destroy"
    end
    resource :shift_metric
  end

  resources :manager_profiles, only: [:new, :create]
  resources :bartender_profiles, only: [:new, :create]
end

app/models/bar.rb
class Bar < ActiveRecord::Base
  has_many :bar_gig_memberships, dependent: :destroy
  has_many :users, through: :bar_gig_memberships

  belongs_to :owner, class_name: "User", foreign_key: :user_id

  has_many :shifts

  delegate :name, to: :owner, prefix: true

  validates :address, presence: true
  validates :city, presence: true
  validates :name, presence: true
  validates_uniqueness_of(
    :name,
    scope: [:address, :city, :state]
  )
  validates :phone, presence: true
  validates :state, presence: true
  validates :user_id, presence: true
  validates :zip, presence: true

  def add_member(user)
    users << user
  end

  def remove_member(user)
    users.delete(user)
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @bars = Bar.all
    @bar = Bar.new
  end

  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)

    if @bar.save
      redirect_to @bar
    else
      render :new
    end
  end

  def show
    bar
  end

  def edit
    bar
    if current_user.owns?(@bar)
      bar
    else
      redirect_to @bar
    end
  end

  def update
    bar
    if current_user.owns?(@bar)
      bar.update(bar_params)
    end

    if @bar.save
      redirect_to @bar
    else
      render :edit
    end
  end

  def destroy
    bar
    if current_user.owns?(@bar)
      bar.destroy
    end

    redirect_to bars_path
  end

  private

  def bar_params
    params.require(:bar).permit(
      :address,
      :city,
      :name,
      :phone,
      :state,
      :website,
      :zip
    ).merge(user: current_user)
  end

  def bar
    @bar ||= Bar.find(params[:id])
  end
end

app/views/bars/_bar.html.erb
<h4 class="profile"><%= link_to bar.name, bar %></h4>

<section class="container">
  <%= bar.address %>
  <div>
    <%= bar.city %>,
    <%= bar.state %>
    <%= bar.zip %>
  </div>
  <div>
    <%= bar.phone %>
  </div>
  <div>
    <%= bar.website %>
  </div>
  <% if current_user.owns_or_works_at?(bar) %>
    <div>
      <p>Owner: <%= bar.owner_name %></p>
      <p>Bartenders:
        <ul><%= render bar.users %></ul>
      </p>
    </div>
  <% end %>
</section>

app/views/bars/_bars.html.erb
<section class="container">
  <% bars.each do |bar| %>
    <h1 class="title-ha">
      <%= link_to bar.name, bar %>
      &mdash; <%= bar.city %>, <%= bar.state %>
    </h1>
  <% end %>
</section>

app/views/bars/_bartender.html.erb
<section class="container">
    <% if user.works_at?(bar) %>
      <p>
        <%= button_to(
          "Leave Bar",
          leave_bar_path(bar),
          method: :delete,
          class: "button"
        ) %>
      </p>
      <p class="title-ha">
        <%= link_to(
          "Available Shifts",
          bar_shifts_path(bar),
          class: "button secondary"
        ) %>
      </p>
    <% else %>
      <p>
        <%= button_to(
          "Join Bar",
          join_bar_path(bar),
          method: :post,
          class: "button"
        ) %>
      </p>
    <% end %>
</section>

app/views/bars/_form.html.erb
<%= form_for bar, html: { class: "no-info" } do |form| %>
  <% if bar.errors.any? %>
    <p>
      <%= render "error_messages", errors: bar.errors %>
    </p>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
  <div>
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>
  <div>
    <%= form.label :phone %>
    <%= form.telephone_field :phone %>
  </div>
  <div>
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bars/_manager.html.erb
<section class="container">
  <% if current_user.owns?(bar) %>
    <p class="title-ha">
      <%= link_to "Reports",
        report_bar_path(bar),
        class: "button secondary" %>
    </p>
    <p>
      <%= link_to "Current Shifts",
        bar_shifts_path(bar),
        class: "button secondary" %>
    </p>
    <p>
      <%= link_to "Update Bar Information",
        edit_bar_path(bar),
        class: "button" %>
    </p>
    <p>
      <%= button_to "Delete Bar", bar_path(bar),
        method: :delete,
        data: { confirm: "Please confirm deletion" } %>
    </p>
  <% end %>
</section>

app/views/bars/edit.html.erb
<h1 class="profile">Update <%= @bar.name %>'s Info</h1>

<%= render "form", bar: @bar %>

app/views/bars/index.html.erb
<h1 class="profile">Guesting Bars</h1>

<%= render "bars", bars: @bars %>

app/views/bars/new.html.erb
<h1 class="profile">Enter Your Bar's Information</h1>

<%= render "form", bar: @bar %>

app/views/bars/show.html.erb
<%= render @bar, user: current_user %>

<% if current_user.manager? %>
  <%= render "manager", bar: @bar, user: current_user %>
<% else %>
  <%= render "bartender", bar: @bar, user: current_user %>
<% end %>