config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "landings#show"
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :bars do
    member do
      post "join" => "bar_gig_memberships#create"
      delete "leave" => "bar_gig_memberships#destroy"
    end
    member do
      get "report" => "reports#show"
    end
    resources :shifts
  end

  resources :shifts do
    member do
      post "take" => "shift_memberships#create"
      delete "return" => "shift_memberships#destroy"
    end
    resource :shift_metric
  end

  resources :manager_profiles, only: [:new, :create]
  resources :bartender_profiles, only: [:new, :create]
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :bar

  has_one :shift_metric

  has_many :shift_memberships, dependent: :destroy
  has_many :users, through: :shift_memberships

  delegate :name, to: :bar, prefix: true
  delegate :name, to: :user, prefix: true
  delegate :sales, to: :shift_metric
  delegate :patron_count, to: :shift_metric

  validates :bar_id, presence: true
  validates :shift_date, presence: true
  validates_uniqueness_of(:shift_date, scope: :shift_start)
  validates :shift_start, presence: true

  def self.by_most_recent
    order(shift_date: :asc)
  end

  def add_bartender(user)
    users << user
  end

  def remove_bartender(user)
    users.delete(user)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :require_bar_owner, only: [:new, :create]
  before_action :require_owner, only: [:edit, :update, :destroy]
  before_action :require_membership, only: [:show]

  def index
    find_bar
    @shifts = @bar.shifts
  end

  def new
    @shift = Shift.new(bar_id: bar_id)
  end

  def create
    @shift = Shift.new(shift_params)

    if @shift.save
      redirect_to [@shift.bar, @shift]
    else
      render :new
    end
  end

  def show
    @shift_metric_path = shift_metric_profile_path(@shift)
  end

  def edit
  end

  def update
    if @shift.update(shift_params)
      redirect_to [@shift.bar, @shift]
    else
      render :edit
    end
  end

  def destroy
    @shift.destroy

    redirect_to bar_shifts_path(@shift.bar)
  end

  def shift_metric_profile_path(shift)
    if shift.shift_metric.nil?
      new_shift_shift_metric_path(shift)
    else
      shift_shift_metric_path(shift)
    end
  end

  private

  def require_bar_owner
    find_bar
    unless current_user.owns?(@bar)
      redirect_to @bar
    end
  end

  def require_owner
    find_shift
    unless current_user.owns?(@shift.bar)
      redirect_to [@shift.bar, @shift]
    end
  end

  def require_membership
    find_shift
    unless current_user.owns_or_works_at?(@shift.bar)
      redirect_to @shift.bar
    end
  end

  def find_bar
    @bar ||=
      current_user.owned_bars.find_by(id: bar_id) ||
      current_user.bars.find_by(id: bar_id)
  end

  def bar_id
    params[:bar_id]
  end

  def find_shift
    @shift ||= Shift.find(params[:id])
  end

  def shift_params
    params.require(:shift).permit(
      :bartender_count,
      :details,
      :shift_date,
      :shift_start
    ).merge(bar_id: bar_id)
  end
end

app/views/shifts/_available_shifts.html.erb
<section class="container">
  <% shifts.each do |shift| %>
    <% if shift.users.count < shift.bartender_count %>
      <h3 class="title-ha">
        <%= link_to "#{shift.shift_date.strftime("%A, %-m/%d/%Y")},
          Time: #{shift.shift_start.strftime("%l:%M %P")}",
          [bar, shift] %>
      </h3>
    <% end %>
  <% end %>
</section>

app/views/shifts/_bartender.html.erb
<section class="container">

  <%= render shift, bar: shift.bar %>

  <% if user.working?(shift) %>
    <%= button_to(
      "Give Shift Back",
      return_shift_path(shift),
      method: :delete,
      class: "button"
    ) %>
  <% else %>
    <%= button_to(
      "Take Shift",
      take_shift_path(shift),
      method: :post,
      class: "button"
    ) %>
  <% end %>

  <p class="title-ha">
    <%= link_to(
      "Return to Shifts",
      bar_shifts_path(shift.bar),
      class: "button secondary"
    ) %>
  </p>
</section>

app/views/shifts/_form.html.erb
<%= form_for [bar, shift], html: { class: "no-info" } do |form| %>
  <% if shift.errors.any? %>
    <p>
      <%= render "error_messages", errors: shift.errors %>
    </p>
  <% end %>
  <div>
    <%= form.label :shift_date, "Date" %>
    <%= form.date_field :shift_date %>
  </div>
  <div>
    <%= form.label :shift_start, "Start Time" %>
    <%= form.time_field :shift_start %>
  </div>
  <div>
    <%= form.label :details, "Details/Special Instructions" %>
    <%= form.text_area :details %>
  </div>
  <div>
    <%= form.label :bartender_count, "# Bartenders Needed" %>
    <%= form.number_field :bartender_count %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shifts/_manager.html.erb
<section class="container">

  <%= render shift, bar: shift.bar %>

  <% if user.owns?(shift.bar) %>
    <p class="button">
      <%= link_to "Update Shift", edit_bar_shift_path(shift.bar, shift) %>
    </p>
    <p class="button secondary">
      <%= link_to "Shift Results", @shift_metric_path %>
    </p>
    <p>
      <%= button_to(
        "Delete Shift",
        bar_shift_path(shift.bar, shift),
        method: :delete,
        data: { confirm: "Are you sure" }
      ) %>
    </p>
    <p class="title-ha">
    <%= link_to(
      "Return to Shifts",
      bar_shifts_path(shift.bar),
      class: "button secondary"
    ) %>
    </p>
  <% end %>
</section>

app/views/shifts/_shift.html.erb
<section class="container">
  <div>
    <p>
    <%= "Date: #{shift.shift_date.strftime("%A, %-m/%d/%Y")},
    Time: #{shift.shift_start.strftime("%l:%M %P")}" %>
    </p>
  </div>
  <div>
    <p>Details: <%= shift.details %></p>
  </div>
  <div>
    <p>Guest Bartenders Needed: <%= shift.bartender_count %></p>
  </div>
  <% if current_user.owns_or_works_at?(bar) %>
    <div>
      <p>Guest Bartenders Assigned: <%= shift.users.count %></p>
      <ul>
        <li><%= render shift.users %><li>
      </ul>
    </div>
  <% end %>
</section>

app/views/shifts/_shifts.html.erb
<section class="container">
  <% shifts.each do |shift| %>
    <h3 class="title-ha">
      <%= link_to "#{shift.shift_date.strftime("%A, %-m/%d/%Y")},
        Time: #{shift.shift_start.strftime("%l:%M %P")}",
        [bar, shift] %>
    </h3>
  <% end %>
</section>

app/views/shifts/edit.html.erb
<h1 class="profile">Update Shift Details</h1>

<%= render "form", bar: @shift.bar, shift: @shift %>

app/views/shifts/index.html.erb
<h1 class="profile"><%= link_to @bar.name, @bar %></h1>

<section class="container">
  <h2 class="results">Available Shifts</h2>

  <%= render "available_shifts", shifts: @shifts.by_most_recent, bar: @bar %>

  <% if current_user.owns?(@bar) %>
    <h2 class="results">All Shifts</h2>

    <%= render "shifts", shifts: @shifts.by_most_recent, bar: @bar %>

    <div>
      <%= link_to "Create Shift", new_bar_shift_path(@bar), class: "button" %>
    </div>
  <% end %>
</section>

app/views/shifts/new.html.erb
<h1 class="profile">New Shift Details</h1>

<%= render "form", bar: @shift.bar, shift: @shift %>

app/views/shifts/show.html.erb
<h1 class="profile"><%= link_to @shift.bar_name, @shift.bar %></h1>

<% if current_user.manager? %>
  <%= render "manager", shift: @shift, user: current_user %>
<% else %>
  <%= render "bartender", shift: @shift, user: current_user %>
<% end %>