config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "landings#show"
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :bars do
    member do
      post "join" => "bar_gig_memberships#create"
      delete "leave" => "bar_gig_memberships#destroy"
    end
    member do
      get "report" => "reports#show"
    end
    resources :shifts
  end

  resources :shifts do
    member do
      post "take" => "shift_memberships#create"
      delete "return" => "shift_memberships#destroy"
    end
    resource :shift_metric
  end

  resources :manager_profiles, only: [:new, :create]
  resources :bartender_profiles, only: [:new, :create]
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/views/dashboards/_bartender.html.erb
<section class="container">
  <h2 class="results">Your Shifts</h2>

  <%= render "shifts", shifts: user.shifts.by_most_recent %>

  <h2 class="results">Your Bars</h2>

  <%= render user.bars.order(name: :asc) %>

  <h2>
    <%= link_to "The Guesting Bars", bars_path, class: "button" %>
  </h2>
</section>

app/views/dashboards/_manager.html.erb
<section class="container">
  <h1 class="results">Your Bars</h1>

  <%= render user.owned_bars %>

  <h4>
    <%= link_to "Create New Bar", new_bar_path, class: "button" %>
  </h4>
</section>

app/views/dashboards/_shifts.html.erb
<section class="container">
  <div>
    <% shifts.each do |shift| %>
      <p>
        <%= link_to "Bar: #{shift.bar_name}", shift.bar %> &mdash;
        <%= link_to "Date: #{shift.shift_date.strftime("%A, %-m/%d/%Y")},
          Time: #{shift.shift_start.strftime("%l:%M %P")}", shift %>
      </p>
    <% end %>
  </div>
</section>

app/views/dashboards/show.html.erb
<h1 class="profile">Welcome <%= current_user.name %></h1>

<% if current_user.manager? %>
  <%= render "manager", user: current_user %>
<% else %>
  <%= render "bartender", user: current_user %>
<% end %>